"""init

Revision ID: 644b55aae6e4
Revises:
Create Date: 2025-11-07 20:41:30.625936

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "644b55aae6e4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bucket_type", sa.String(length=20), nullable=False),
        sa.Column("bucket_id", sa.String(length=255), nullable=False),
        sa.Column("logical_path", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("source_file_id", sa.String(length=36), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "bucket_type IN ('users', 'companies', 'projects')",
            name="check_bucket_type",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'upload_pending', 'pending_validation', 'approved', 'rejected', 'requires_revision', 'archived')",
            name="check_status",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bucket_type", "bucket_id", "logical_path", name="unique_file_path"
        ),
    )
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.create_index(
            "idx_files_bucket", ["bucket_type", "bucket_id"], unique=False
        )
        batch_op.create_index("idx_files_owner", ["owner_id"], unique=False)
        batch_op.create_index("idx_files_status", ["status"], unique=False)
        batch_op.create_index(
            "idx_files_updated", ["updated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_files_bucket_id"), ["bucket_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_files_bucket_type"), ["bucket_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_files_logical_path"), ["logical_path"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_files_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "file_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "pending_validation",
                "validated",
                "rejected",
                name="version_status",
            ),
            nullable=False,
        ),
        sa.Column("validation_comment", sa.Text(), nullable=True),
        sa.Column("validated_by", sa.String(length=36), nullable=True),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "file_id", "version_number", name="_file_version_uc"
        ),
    )
    with op.batch_alter_table("file_versions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_file_versions_created_at", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_file_versions_file_id", ["file_id"], unique=False
        )
        batch_op.create_index(
            "idx_file_versions_object_key", ["object_key"], unique=False
        )
        batch_op.create_index(
            "idx_file_versions_status", ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_file_versions_object_key"),
            ["object_key"],
            unique=False,
        )

    op.create_table(
        "locks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("locked_by", sa.String(length=36), nullable=False),
        sa.Column(
            "lock_type",
            sa.Enum("edit", "review", "admin", name="lock_type"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("locks", schema=None) as batch_op:
        batch_op.create_index(
            "idx_locks_expires_at", ["expires_at"], unique=False
        )
        batch_op.create_index("idx_locks_file_id", ["file_id"], unique=False)
        batch_op.create_index(
            "idx_locks_is_active", ["is_active"], unique=False
        )
        batch_op.create_index(
            "idx_locks_locked_by", ["locked_by"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "upload",
                "download",
                "copy",
                "move",
                "delete",
                "lock",
                "unlock",
                "validate",
                "approve",
                "reject",
                "restore",
                name="audit_action",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["version_id"], ["file_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_audit_logs_action", ["action"], unique=False
        )
        batch_op.create_index(
            "idx_audit_logs_created_at", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_audit_logs_file_id", ["file_id"], unique=False
        )
        batch_op.create_index(
            "idx_audit_logs_file_user", ["file_id", "user_id"], unique=False
        )
        batch_op.create_index(
            "idx_audit_logs_user_id", ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_audit_logs_user_id")
        batch_op.drop_index("idx_audit_logs_file_user")
        batch_op.drop_index("idx_audit_logs_file_id")
        batch_op.drop_index("idx_audit_logs_created_at")
        batch_op.drop_index("idx_audit_logs_action")

    op.drop_table("audit_logs")
    with op.batch_alter_table("locks", schema=None) as batch_op:
        batch_op.drop_index("idx_locks_locked_by")
        batch_op.drop_index("idx_locks_is_active")
        batch_op.drop_index("idx_locks_file_id")
        batch_op.drop_index("idx_locks_expires_at")

    op.drop_table("locks")
    with op.batch_alter_table("file_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_versions_object_key"))
        batch_op.drop_index("idx_file_versions_status")
        batch_op.drop_index("idx_file_versions_object_key")
        batch_op.drop_index("idx_file_versions_file_id")
        batch_op.drop_index("idx_file_versions_created_at")

    op.drop_table("file_versions")
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_files_owner_id"))
        batch_op.drop_index(batch_op.f("ix_files_logical_path"))
        batch_op.drop_index(batch_op.f("ix_files_bucket_type"))
        batch_op.drop_index(batch_op.f("ix_files_bucket_id"))
        batch_op.drop_index("idx_files_updated")
        batch_op.drop_index("idx_files_status")
        batch_op.drop_index("idx_files_owner")
        batch_op.drop_index("idx_files_bucket")

    op.drop_table("files")
    op.drop_table("dummy")
    # ### end Alembic commands ###
